version: "2"
services:
  eureka-node1:      # 默认情况下，其他服务可以使用服务名称连接到该服务。因此，对于peer2的节点，它需要连接http://peer1:8761/eureka/，因此需要配置该服务的名称是peer1。
    image: micro-service-cloud/micro-service-cloud-eureka
    hostname: node1
    networks:
      - eureka-net
    ports:
      - "8000:8000"
    environment:
      - spring.profiles.active=node1
  eureka-node2:
    image: micro-service-cloud/micro-service-cloud-eureka
    networks:
         - eureka-net
    hostname: node2
    networks:
      - eureka-net
    ports:
      - "8001:8001"
    environment:
      - spring.profiles.active=node2
networks:
  eureka-net:
    driver: bridge