server:
  port: 8888

##appFilePath: /var/www/html/app/
appFilePath: E:\MyDownloads\Download\

##firmwareFilePath: /var/www/html/firmware/
firmwareFilePath: E:\MyDownloads\Downloads\

spring:
  application:
    name: MscCommonService
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

eureka:
  instance:
    hostname: msccommon
    prefer-ip-address: true
    ip-address: 39.104.164.214

  client:
    service-url:
        defaultZone: http://msc-eureka-1:8000/eureka/
