spring:
  application:
    name: msc-auth

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud-oauth2 ? useUnicode=true & characterEncoding=utf8 & characterSetResults=utf8
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9000

security:
  oauth2:
    resource:
      filter-order: 3

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

  client:
    service-url:
        defaultZone: http://msc-eureka1:8000/eureka/,http://msc-eureka2:8001/eureka/


